{% set name = "yfinance" %}
{% set version = "0.2.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "207da19e87792bf742d2744eee2fe18169853c1b82cfe14a9a7cfb8d05f09137"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pandas >=1.3.0
    - numpy >=1.16.5
    - requests >=2.26
    - multitasking >=0.0.7
    - lxml >=4.9.1
    - appdirs >=1.4.4
    - pytz >=2022.5
    - frozendict >=2.3.4
    - beautifulsoup4 >=4.11.1
    - html5lib >=1.1
    # - pycryptodome >=3.6.6
    - cryptography >=3.3.2
    - pip
    - python

  run:
    - pandas >=1.3.0
    - numpy >=1.16.5
    - requests >=2.26
    - multitasking >=0.0.7
    - lxml >=4.9.1
    - appdirs >=1.4.4
    - pytz >=2022.5
    - frozendict >=2.3.4
    - beautifulsoup4 >=4.11.1
    - html5lib >=1.1
    # - pycryptodome >=3.6.6
    - cryptography >=3.3.2
    - python

test:
  imports:
    - yfinance

about:
  home: "https://github.com/ranaroussi/yfinance"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "Yahoo! Finance market data downloader"
  description:
  doc_url: "https://github.com/ranaroussi/yfinance"
  dev_url: "https://pypi.python.org/pypi/yfinance"
  doc_source_url: https://github.com/ranaroussi/yfinance/blob/master/README.rst


extra:
  recipe-maintainers:
    - ranaroussi
