sudo apt install -y libmpdec3:amd64
sudo apt install -y libmpeg2encpp-2.1-0:amd64
sudo apt install -y libmpfr6:amd64
sudo apt install -y libmpg123-0:amd64
sudo apt install -y libmplex2-2.1-0:amd64
sudo apt install -y libmspack0:amd64
sudo apt install -y libmtdev1:amd64
sudo apt install -y libmtp-common
sudo apt install -y libmtp-runtime
sudo apt install -y libmtp9:amd64
sudo apt install -y libmujs1:amd64
sudo apt install -y libmutter-10-0:amd64
sudo apt install -y libmysofa1:amd64
sudo apt install -y libnautilus-extension1a:amd64
sudo apt install -y libncurses6:amd64
sudo apt install -y libncursesw6:amd64
sudo apt install -y libndp0:amd64
sudo apt install -y libnet-dbus-perl
sudo apt install -y libnet-http-perl
sudo apt install -y libnet-smtp-ssl-perl
sudo apt install -y libnet-ssleay-perl:amd64
sudo apt install -y libnet1:amd64
sudo apt install -y libnetfilter-conntrack3:amd64
sudo apt install -y libnetplan0:amd64
sudo apt install -y libnettle8:amd64
sudo apt install -y libnewt0.52:amd64
sudo apt install -y libnfnetlink0:amd64
sudo apt install -y libnfs13:amd64
sudo apt install -y libnftables1:amd64
sudo apt install -y libnftnl11:amd64
sudo apt install -y libnghttp2-14:amd64
sudo apt install -y libnginx-mod-http-geoip2
sudo apt install -y libnginx-mod-http-image-filter
sudo apt install -y libnginx-mod-http-xslt-filter
sudo apt install -y libnginx-mod-mail
sudo apt install -y libnginx-mod-stream
sudo apt install -y libnginx-mod-stream-geoip2
sudo apt install -y libnice10:amd64
sudo apt install -y libnl-3-200:amd64
sudo apt install -y libnl-genl-3-200:amd64
sudo apt install -y libnl-route-3-200:amd64
sudo apt install -y libnm0:amd64
sudo apt install -y libnma-common
sudo apt install -y libnma0:amd64
sudo apt install -y libnorm1:amd64
sudo apt install -y libnotify-bin
sudo apt install -y libnotify-dev:amd64
sudo apt install -y libnotify4:amd64
sudo apt install -y libnpth0:amd64
sudo apt install -y libnsl-dev:amd64
sudo apt install -y libnsl2:amd64
sudo apt install -y libnspr4:amd64
sudo apt install -y libnss-mdns:amd64
sudo apt install -y libnss-systemd:amd64
sudo apt install -y libnss3:amd64
sudo apt install -y libntfs-3g89
sudo apt install -y libnuma1:amd64
sudo apt install -y libnvidia-cfg1-470:amd64
sudo apt install -y libnvidia-common-470
sudo apt install -y libnvidia-compute-470:amd64
sudo apt install -y libnvidia-decode-470:amd64
sudo apt install -y libnvidia-egl-wayland1:amd64
sudo apt install -y libnvidia-encode-470:amd64
sudo apt install -y libnvidia-extra-470:amd64
sudo apt install -y libnvidia-fbc1-470:amd64
sudo apt install -y libnvidia-gl-470:amd64
sudo apt install -y libnvidia-ifr1-470:amd64
sudo apt install -y libogg0:amd64
sudo apt install -y libonig5:amd64
sudo apt install -y libopenal-data
sudo apt install -y libopenal1:amd64
sudo apt install -y libopenexr25:amd64
sudo apt install -y libopengl-dev:amd64
sudo apt install -y libopengl0:amd64
sudo apt install -y libopenh264-6:amd64
sudo apt install -y libopeniscsiusr
sudo apt install -y libopenjp2-7:amd64
sudo apt install -y libopenmpt0:amd64
sudo apt install -y libopenni2-0:amd64
sudo apt install -y libopts25:amd64
sudo apt install -y libopus0:amd64
sudo apt install -y liborc-0.4-0:amd64
sudo apt install -y libp11-kit0:amd64
sudo apt install -y libpackagekit-glib2-18:amd64
sudo apt install -y libpam-cap:amd64
sudo apt install -y libpam-gnome-keyring:amd64
sudo apt install -y libpam-modules:amd64
sudo apt install -y libpam-modules-bin
sudo apt install -y libpam-runtime
sudo apt install -y libpam-systemd:amd64
sudo apt install -y libpam0g:amd64
sudo apt install -y libpango-1.0-0:amd64
sudo apt install -y libpango1.0-dev:amd64
sudo apt install -y libpangocairo-1.0-0:amd64
sudo apt install -y libpangoft2-1.0-0:amd64
sudo apt install -y libpangomm-1.4-1v5:amd64
sudo apt install -y libpangoxft-1.0-0:amd64
sudo apt install -y libpaper-utils
sudo apt install -y libpaper1:amd64
sudo apt install -y libparted-fs-resize0:amd64
sudo apt install -y libparted2:amd64
sudo apt install -y libpcap0.8:amd64
sudo apt install -y libpci3:amd64
sudo apt install -y libpciaccess0:amd64
sudo apt install -y libpcre16-3:amd64
sudo apt install -y libpcre2-16-0:amd64
sudo apt install -y libpcre2-32-0:amd64
sudo apt install -y libpcre2-8-0:amd64
sudo apt install -y libpcre2-dev:amd64
sudo apt install -y libpcre2-posix3:amd64
sudo apt install -y libpcre3:amd64
sudo apt install -y libpcre3-dev:amd64
sudo apt install -y libpcre32-3:amd64
sudo apt install -y libpcrecpp0v5:amd64
sudo apt install -y libpcsclite1:amd64
sudo apt install -y libpeas-1.0-0:amd64
sudo apt install -y libpeas-common
sudo apt install -y libperl5.34:amd64
sudo apt install -y libpgm-5.3-0:amd64
sudo apt install -y libphonenumber8:amd64
sudo apt install -y libpipeline1:amd64
sudo apt install -y libpipewire-0.3-0:amd64
sudo apt install -y libpipewire-0.3-common
sudo apt install -y libpipewire-0.3-modules:amd64
sudo apt install -y libpixman-1-0:amd64
sudo apt install -y libpixman-1-dev:amd64
sudo apt install -y libplacebo192:amd64
sudo apt install -y libplist3:amd64
sudo apt install -y libplymouth5:amd64
sudo apt install -y libpng-dev:amd64
sudo apt install -y libpng-tools
sudo apt install -y libpng16-16:amd64
sudo apt install -y libpocketsphinx3:amd64
sudo apt install -y libpolkit-agent-1-0:amd64
sudo apt install -y libpolkit-gobject-1-0:amd64
sudo apt install -y libpoppler-cpp0v5:amd64
sudo apt install -y libpoppler-glib8:amd64
sudo apt install -y libpoppler118:amd64
sudo apt install -y libpopt0:amd64
sudo apt install -y libpostproc55:amd64
sudo apt install -y libpq5:amd64
sudo apt install -y libproc-processtable-perl:amd64
sudo apt install -y libprocps8:amd64
sudo apt install -y libprotobuf23:amd64
sudo apt install -y libproxy1v5:amd64
sudo apt install -y libpsl5:amd64
sudo apt install -y libpthread-stubs0-dev:amd64
sudo apt install -y libpulse-mainloop-glib0:amd64
sudo apt install -y libpulse0:amd64
sudo apt install -y libpulsedsp:amd64
sudo apt install -y libpwquality-common
sudo apt install -y libpwquality1:amd64
sudo apt install -y libpython3-dev:amd64
sudo apt install -y libpython3-stdlib:amd64
sudo apt install -y libpython3.10:amd64
sudo apt install -y libpython3.10-dev:amd64
sudo apt install -y libpython3.10-minimal:amd64
sudo apt install -y libpython3.10-stdlib:amd64
sudo apt install -y libqmi-glib5:amd64
sudo apt install -y libqmi-proxy
sudo apt install -y libqpdf28:amd64
sudo apt install -y libqrencode4:amd64
sudo apt install -y libqt5core5a:amd64
sudo apt install -y libqt5dbus5:amd64
sudo apt install -y libqt5designer5:amd64
sudo apt install -y libqt5gui5:amd64
sudo apt install -y libqt5help5:amd64
sudo apt install -y libqt5network5:amd64
sudo apt install -y libqt5positioning5:amd64
sudo apt install -y libqt5printsupport5:amd64
sudo apt install -y libqt5qml5:amd64
sudo apt install -y libqt5qmlmodels5:amd64
sudo apt install -y libqt5quick5:amd64
sudo apt install -y libqt5quickwidgets5:amd64
sudo apt install -y libqt5sql5:amd64
sudo apt install -y libqt5sql5-sqlite:amd64
sudo apt install -y libqt5svg5:amd64
sudo apt install -y libqt5test5:amd64
sudo apt install -y libqt5webchannel5:amd64
sudo apt install -y libqt5webengine-data
sudo apt install -y libqt5webengine5:amd64
sudo apt install -y libqt5webenginecore5:amd64
sudo apt install -y libqt5webenginewidgets5:amd64
sudo apt install -y libqt5widgets5:amd64
sudo apt install -y libqt5xml5:amd64
sudo apt install -y libquadmath0:amd64
sudo apt install -y librabbitmq4:amd64
sudo apt install -y libraw1394-11:amd64
sudo apt install -y libre2-9:amd64
sudo apt install -y libreadline8:amd64
sudo apt install -y librest-0.7-0:amd64
sudo apt install -y librsvg2-2:amd64
sudo apt install -y librsvg2-common:amd64
sudo apt install -y librtmp1:amd64
sudo apt install -y librubberband2:amd64
sudo apt install -y librygel-core-2.6-2:amd64
sudo apt install -y librygel-db-2.6-2:amd64
sudo apt install -y librygel-renderer-2.6-2:amd64
sudo apt install -y librygel-server-2.6-2:amd64
sudo apt install -y libsamplerate0:amd64
sudo apt install -y libsane-common
sudo apt install -y libsane1:amd64
sudo apt install -y libsasl2-2:amd64
sudo apt install -y libsasl2-modules:amd64
sudo apt install -y libsasl2-modules-db:amd64
sudo apt install -y libsbc1:amd64
sudo apt install -y libsdl2-2.0-0:amd64
sudo apt install -y libseccomp2:amd64
sudo apt install -y libsecret-1-0:amd64
sudo apt install -y libsecret-1-dev:amd64
sudo apt install -y libsecret-common
sudo apt install -y libsecret-tools
sudo apt install -y libselinux1:amd64
sudo apt install -y libselinux1-dev:amd64
sudo apt install -y libsemanage-common
sudo apt install -y libsemanage2:amd64
sudo apt install -y libsensors-config
sudo apt install -y libsensors5:amd64
sudo apt install -y libsepol-dev:amd64
sudo apt install -y libsepol2:amd64
sudo apt install -y libserd-0-0:amd64
sudo apt install -y libsgutils2-2:amd64
sudo apt install -y libshine3:amd64
sudo apt install -y libshout3:amd64
sudo apt install -y libsigc++-2.0-0v5:amd64
sudo apt install -y libsigsegv2:amd64
sudo apt install -y libsixel1:amd64
sudo apt install -y libslang2:amd64
sudo apt install -y libsm-dev:amd64
sudo apt install -y libsm6:amd64
sudo apt install -y libsmartcols1:amd64
sudo apt install -y libsmbclient:amd64
sudo apt install -y libsmbios-c2
sudo apt install -y libsnapd-glib1:amd64
sudo apt install -y libsnappy1v5:amd64
sudo apt install -y libsndfile1:amd64
sudo apt install -y libsndio7.0:amd64
sudo apt install -y libsnmp-base
sudo apt install -y libsnmp40:amd64
sudo apt install -y libsodium23:amd64
sudo apt install -y libsord-0-0:amd64
sudo apt install -y libsort-naturally-perl
sudo apt install -y libsoundtouch1:amd64
sudo apt install -y libsoup-3.0-0:amd64
sudo apt install -y libsoup-3.0-common
sudo apt install -y libsoup-gnome2.4-1:amd64
sudo apt install -y libsoup2.4-1:amd64
sudo apt install -y libsoup2.4-common
sudo apt install -y libsoxr0:amd64
sudo apt install -y libspa-0.2-modules:amd64
sudo apt install -y libspandsp2:amd64
sudo apt install -y libspeex1:amd64
sudo apt install -y libspeexdsp1:amd64
sudo apt install -y libsphinxbase3:amd64
sudo apt install -y libsqlite3-0:amd64
sudo apt install -y libsratom-0-0:amd64
sudo apt install -y libsrt1.4-gnutls:amd64
sudo apt install -y libsrtp2-1:amd64
sudo apt install -y libss2:amd64
sudo apt install -y libssh-4:amd64
sudo apt install -y libssh-gcrypt-4:amd64
sudo apt install -y libssh2-1:amd64
sudo apt install -y libssl3:amd64
sudo apt install -y libstartup-notification0:amd64
sudo apt install -y libstdc++-11-dev:amd64
sudo apt install -y libstdc++6:amd64
sudo apt install -y libstemmer0d:amd64
sudo apt install -y libswresample3:amd64
sudo apt install -y libswscale5:amd64
sudo apt install -y libsystemd0:amd64
sudo apt install -y libtag1v5:amd64
sudo apt install -y libtag1v5-vanilla:amd64
sudo apt install -y libtagc0:amd64
sudo apt install -y libtalloc2:amd64
sudo apt install -y libtasn1-6:amd64
sudo apt install -y libtcl8.6:amd64
sudo apt install -y libtdb1:amd64
sudo apt install -y libteamdctl0:amd64
sudo apt install -y libterm-readkey-perl
sudo apt install -y libtevent0:amd64
sudo apt install -y libtext-charwidth-perl
sudo apt install -y libtext-iconv-perl
sudo apt install -y libtext-wrapi18n-perl
sudo apt install -y libthai-data
sudo apt install -y libthai-dev:amd64
sudo apt install -y libthai0:amd64
sudo apt install -y libtheora0:amd64
sudo apt install -y libthunarx-3-0:amd64
sudo apt install -y libtie-ixhash-perl
sudo apt install -y libtiff-dev:amd64
sudo apt install -y libtiff5:amd64
sudo apt install -y libtiffxx5:amd64
sudo apt install -y libtimedate-perl
sudo apt install -y libtimezonemap-data
sudo apt install -y libtimezonemap1:amd64
sudo apt install -y libtinfo6:amd64
sudo apt install -y libtirpc-common
sudo apt install -y libtirpc-dev:amd64
sudo apt install -y libtirpc3:amd64
sudo apt install -y libtk8.6:amd64
sudo apt install -y libtry-tiny-perl
sudo apt install -y libtsan0:amd64
sudo apt install -y libtsan2:amd64
sudo apt install -y libtss2-esys-3.0.2-0:amd64
sudo apt install -y libtss2-mu0:amd64
sudo apt install -y libtss2-sys1:amd64
sudo apt install -y libtss2-tcti-cmd0:amd64
sudo apt install -y libtss2-tcti-device0:amd64
sudo apt install -y libtss2-tcti-mssim0:amd64
sudo apt install -y libtss2-tcti-swtpm0:amd64
sudo apt install -y libtumbler-1-0:amd64
sudo apt install -y libtwolame0:amd64
sudo apt install -y libubsan1:amd64
sudo apt install -y libuchardet0:amd64
sudo apt install -y libudev1:amd64
sudo apt install -y libudfread0:amd64
sudo apt install -y libudisks2-0:amd64
sudo apt install -y libunistring2:amd64
sudo apt install -y libunity-control-center1
sudo apt install -y libunity-gtk2-parser0:amd64
sudo apt install -y libunity-gtk3-parser0:amd64
sudo apt install -y libunity-settings-daemon1:amd64
sudo apt install -y libunwind8:amd64
sudo apt install -y libupower-glib3:amd64
sudo apt install -y liburcu8:amd64
sudo apt install -y liburi-perl
sudo apt install -y libusb-1.0-0:amd64
sudo apt install -y libusbmuxd6:amd64
sudo apt install -y libutempter0:amd64
sudo apt install -y libuuid1:amd64
sudo apt install -y libuv1:amd64
sudo apt install -y libv4l-0:amd64
sudo apt install -y libv4lconvert0:amd64
sudo apt install -y libva-drm2:amd64
sudo apt install -y libva-wayland2:amd64
sudo apt install -y libva-x11-2:amd64
sudo apt install -y libva2:amd64
sudo apt install -y libvdpau1:amd64
sudo apt install -y libvidstab1.1:amd64
sudo apt install -y libvisual-0.4-0:amd64
sudo apt install -y libvncserver1:amd64
sudo apt install -y libvo-aacenc0:amd64
sudo apt install -y libvo-amrwbenc0:amd64
sudo apt install -y libvolume-key1
sudo apt install -y libvorbis0a:amd64
sudo apt install -y libvorbisenc2:amd64
sudo apt install -y libvorbisfile3:amd64
sudo apt install -y libvpx7:amd64
sudo apt install -y libvte-2.91-0:amd64
sudo apt install -y libvte-2.91-common
sudo apt install -y libvulkan1:amd64
sudo apt install -y libwacom-bin
sudo apt install -y libwacom-common
sudo apt install -y libwacom9:amd64
sudo apt install -y libwavpack1:amd64
sudo apt install -y libwayland-bin
sudo apt install -y libwayland-client0:amd64
sudo apt install -y libwayland-cursor0:amd64
sudo apt install -y libwayland-dev:amd64
sudo apt install -y libwayland-egl1:amd64
sudo apt install -y libwayland-server0:amd64
sudo apt install -y libwbclient0:amd64
sudo apt install -y libwebkit2gtk-4.0-37:amd64
sudo apt install -y libwebp7:amd64
sudo apt install -y libwebpdemux2:amd64
sudo apt install -y libwebpmux3:amd64
sudo apt install -y libwebrtc-audio-processing1:amd64
sudo apt install -y libwhoopsie-preferences0
sudo apt install -y libwhoopsie0:amd64
sudo apt install -y libwildmidi2:amd64
sudo apt install -y libwinpr2-2:amd64
sudo apt install -y libwnck-3-0:amd64
sudo apt install -y libwnck-3-common
sudo apt install -y libwoff1:amd64
sudo apt install -y libwrap0:amd64
sudo apt install -y libwww-perl
sudo apt install -y libwww-robotrules-perl
sudo apt install -y libx11-6:amd64
sudo apt install -y libx11-data
sudo apt install -y libx11-dev:amd64
sudo apt install -y libx11-protocol-perl
sudo apt install -y libx11-xcb1:amd64
sudo apt install -y libx264-163:amd64
sudo apt install -y libx265-199:amd64
sudo apt install -y libxapian30:amd64
sudo apt install -y libxatracker2:amd64
sudo apt install -y libxau-dev:amd64
sudo apt install -y libxau6:amd64
sudo apt install -y libxaw7:amd64
sudo apt install -y libxcb-dri2-0:amd64
sudo apt install -y libxcb-dri3-0:amd64
sudo apt install -y libxcb-glx0:amd64
sudo apt install -y libxcb-icccm4:amd64
sudo apt install -y libxcb-image0:amd64
sudo apt install -y libxcb-keysyms1:amd64
sudo apt install -y libxcb-present0:amd64
sudo apt install -y libxcb-randr0:amd64
sudo apt install -y libxcb-render-util0:amd64
sudo apt install -y libxcb-render0:amd64
sudo apt install -y libxcb-render0-dev:amd64
sudo apt install -y libxcb-res0:amd64
sudo apt install -y libxcb-shape0:amd64
sudo apt install -y libxcb-shm0:amd64
sudo apt install -y libxcb-shm0-dev:amd64
sudo apt install -y libxcb-sync1:amd64
sudo apt install -y libxcb-util1:amd64
sudo apt install -y libxcb-xfixes0:amd64
sudo apt install -y libxcb-xinerama0:amd64
sudo apt install -y libxcb-xinput0:amd64
sudo apt install -y libxcb-xkb1:amd64
sudo apt install -y libxcb-xv0:amd64
sudo apt install -y libxcb1:amd64
sudo apt install -y libxcb1-dev:amd64
sudo apt install -y libxcomposite-dev:amd64
sudo apt install -y libxcomposite1:amd64
sudo apt install -y libxcursor-dev:amd64
sudo apt install -y libxcursor1:amd64
sudo apt install -y libxcvt0:amd64
sudo apt install -y libxdamage-dev:amd64
sudo apt install -y libxdamage1:amd64
sudo apt install -y libxdmcp-dev:amd64
sudo apt install -y libxdmcp6:amd64
sudo apt install -y libxext-dev:amd64
sudo apt install -y libxext6:amd64
sudo apt install -y libxfce4panel-2.0-4
sudo apt install -y libxfce4ui-2-0:amd64
sudo apt install -y libxfce4ui-common
sudo apt install -y libxfce4ui-utils
sudo apt install -y libxfce4util-bin
sudo apt install -y libxfce4util-common
sudo apt install -y libxfce4util7:amd64
sudo apt install -y libxfconf-0-3:amd64
sudo apt install -y libxfixes-dev:amd64
sudo apt install -y libxfixes3:amd64
sudo apt install -y libxfont2:amd64
sudo apt install -y libxft-dev:amd64
sudo apt install -y libxft2:amd64
sudo apt install -y libxi-dev:amd64
sudo apt install -y libxi6:amd64
sudo apt install -y libxinerama-dev:amd64
sudo apt install -y libxinerama1:amd64
sudo apt install -y libxkbcommon-dev:amd64
sudo apt install -y libxkbcommon-x11-0:amd64
sudo apt install -y libxkbcommon0:amd64
sudo apt install -y libxkbfile1:amd64
sudo apt install -y libxkbregistry0:amd64
sudo apt install -y libxklavier16:amd64
sudo apt install -y libxml-parser-perl:amd64
sudo apt install -y libxml-twig-perl
sudo apt install -y libxml-xpathengine-perl
sudo apt install -y libxml2:amd64
sudo apt install -y libxmlb2:amd64
sudo apt install -y libxmlsec1:amd64
sudo apt install -y libxmlsec1-openssl:amd64
sudo apt install -y libxmu6:amd64
sudo apt install -y libxmuu1:amd64
sudo apt install -y libxnvctrl0:amd64
sudo apt install -y libxpm4:amd64
sudo apt install -y libxpresent1:amd64
sudo apt install -y libxrandr-dev:amd64
sudo apt install -y libxrandr2:amd64
sudo apt install -y libxrender-dev:amd64
sudo apt install -y libxrender1:amd64
sudo apt install -y libxres1:amd64
sudo apt install -y libxshmfence1:amd64
sudo apt install -y libxslt1.1:amd64
sudo apt install -y libxss1:amd64
sudo apt install -y libxt6:amd64
sudo apt install -y libxtables12:amd64
sudo apt install -y libxtst-dev:amd64
sudo apt install -y libxtst6:amd64
sudo apt install -y libxv1:amd64
sudo apt install -y libxvidcore4:amd64
sudo apt install -y libxvmc1:amd64
sudo apt install -y libxxf86dga1:amd64
sudo apt install -y libxxf86vm1:amd64
sudo apt install -y libxxhash0:amd64
sudo apt install -y libyaml-0-2:amd64
sudo apt install -y libyelp0:amd64
sudo apt install -y libzbar0:amd64
sudo apt install -y libzeitgeist-2.0-0:amd64
sudo apt install -y libzimg2:amd64
sudo apt install -y libzmq5:amd64
sudo apt install -y libzstd1:amd64
sudo apt install -y libzvbi-common
sudo apt install -y libzvbi0:amd64
sudo apt install -y libzxingcore1:amd64
sudo apt install -y lightdm
sudo apt install -y linux-base
sudo apt install -y linux-firmware
sudo apt install -y linux-generic
sudo apt install -y linux-headers-5.15.0-122
sudo apt install -y linux-headers-5.15.0-122-generic
sudo apt install -y linux-headers-5.15.0-124
sudo apt install -y linux-headers-5.15.0-124-generic
sudo apt install -y linux-headers-generic
sudo apt install -y linux-image-5.15.0-122-generic
sudo apt install -y linux-image-5.15.0-124-generic
sudo apt install -y linux-image-generic
sudo apt install -y linux-libc-dev:amd64
sudo apt install -y linux-modules-5.15.0-122-generic
sudo apt install -y linux-modules-5.15.0-124-generic
sudo apt install -y linux-modules-extra-5.15.0-122-generic
sudo apt install -y linux-modules-extra-5.15.0-124-generic
sudo apt install -y lm-sensors
sudo apt install -y locales
sudo apt install -y login
sudo apt install -y logrotate
sudo apt install -y logsave
sudo apt install -y lsb-base
sudo apt install -y lsb-release
sudo apt install -y lshw
sudo apt install -y lsof
sudo apt install -y lto-disabled-list
sudo apt install -y lua-bitop:amd64
sudo apt install -y lua-cjson:amd64
sudo apt install -y lvm2
sudo apt install -y lw-mgmt-self
sudo apt install -y lw-telegraf
sudo apt install -y lxd-agent-loader
sudo apt install -y lynx
sudo apt install -y lynx-common
sudo apt install -y mailcap
sudo apt install -y make
sudo apt install -y man-db
sudo apt install -y manpages
sudo apt install -y manpages-dev
sudo apt install -y mawk
sudo apt install -y mdadm
sudo apt install -y media-types
sudo apt install -y mesa-utils
sudo apt install -y mesa-utils-bin:amd64
sudo apt install -y mesa-va-drivers:amd64
sudo apt install -y mesa-vdpau-drivers:amd64
sudo apt install -y mesa-vulkan-drivers:amd64
sudo apt install -y mime-support
sudo apt install -y mobile-broadband-provider-info
sudo apt install -y modemmanager
sudo apt install -y motd-news-config
sudo apt install -y mount
sudo apt install -y mousepad
sudo apt install -y mousetweaks
sudo apt install -y mpv
sudo apt install -y mtr-tiny
sudo apt install -y multipath-tools
sudo apt install -y mutter-common
sudo apt install -y nano
sudo apt install -y nautilus-data
sudo apt install -y nautilus-extension-gnome-terminal
sudo apt install -y ncurses-base
sudo apt install -y ncurses-bin
sudo apt install -y ncurses-term
sudo apt install -y needrestart
sudo apt install -y net-tools
sudo apt install -y netbase
sudo apt install -y netcat-openbsd
sudo apt install -y netplan-generator
sudo apt install -y netplan.io
sudo apt install -y network-manager
sudo apt install -y network-manager-gnome
sudo apt install -y network-manager-pptp
sudo apt install -y networkd-dispatcher
sudo apt install -y nftables
sudo apt install -y nginx
sudo apt install -y nginx-common
sudo apt install -y nginx-core
sudo apt install -y ngrok
sudo apt install -y nodejs
sudo apt install -y ntfs-3g
sudo apt install -y ntp
sudo apt install -y nvidia-compute-utils-470
sudo apt install -y nvidia-dkms-470
sudo apt install -y nvidia-driver-470
sudo apt install -y nvidia-kernel-common-470
sudo apt install -y nvidia-kernel-source-470
sudo apt install -y nvidia-prime
sudo apt install -y nvidia-settings
sudo apt install -y nvidia-utils-470
sudo apt install -y ocl-icd-libopencl1:amd64
sudo apt install -y open-iscsi
sudo apt install -y open-vm-tools
sudo apt install -y openssh-client
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y openssl
sudo apt install -y os-prober
sudo apt install -y overlayroot
sudo apt install -y p11-kit
sudo apt install -y p11-kit-modules:amd64
sudo apt install -y p7zip
sudo apt install -y p7zip-full
sudo apt install -y packagekit
sudo apt install -y packagekit-tools
sudo apt install -y pango1.0-tools
sudo apt install -y parcellite
sudo apt install -y parted
sudo apt install -y passwd
sudo apt install -y pastebinit
sudo apt install -y patch
sudo apt install -y pavucontrol
sudo apt install -y pci.ids
sudo apt install -y pciutils
sudo apt install -y perl
sudo apt install -y perl-base
sudo apt install -y perl-modules-5.34
sudo apt install -y perl-openssl-defaults:amd64
sudo apt install -y pgadmin4-desktop
sudo apt install -y pgadmin4-server
sudo apt install -y pinentry-curses
sudo apt install -y pinentry-gnome3
sudo apt install -y pipewire:amd64
sudo apt install -y pipewire-bin
sudo apt install -y pipewire-media-session
sudo apt install -y pkexec
sudo apt install -y pkg-config
sudo apt install -y plymouth
sudo apt install -y plymouth-label
sudo apt install -y plymouth-theme-ubuntu-text
sudo apt install -y pocketsphinx-en-us
sudo apt install -y policykit-1
sudo apt install -y policykit-1-gnome
sudo apt install -y polkitd
sudo apt install -y pollinate
sudo apt install -y poppler-data
sudo apt install -y poppler-utils
sudo apt install -y postgresql-client-14
sudo apt install -y postgresql-client-common
sudo apt install -y power-profiles-daemon
sudo apt install -y powermgmt-base
sudo apt install -y ppp
sudo apt install -y pptp-linux
sudo apt install -y procps
sudo apt install -y psmisc
sudo apt install -y publicsuffix
sudo apt install -y pulseaudio
sudo apt install -y pulseaudio-module-bluetooth
sudo apt install -y pulseaudio-utils
sudo apt install -y python-apt-common
sudo apt install -y python-babel-localedata
sudo apt install -y python3
sudo apt install -y python3-apparmor
sudo apt install -y python3-apport
sudo apt install -y python3-apt
sudo apt install -y python3-aptdaemon
sudo apt install -y python3-aptdaemon.gtk3widgets
sudo apt install -y python3-attr
sudo apt install -y python3-automat
sudo apt install -y python3-babel
sudo apt install -y python3-bcrypt
sudo apt install -y python3-blinker
sudo apt install -y python3-brotli
sudo apt install -y python3-cairo:amd64
sudo apt install -y python3-certifi
sudo apt install -y python3-cffi-backend:amd64
sudo apt install -y python3-chardet
sudo apt install -y python3-click
sudo apt install -y python3-colorama
sudo apt install -y python3-commandnotfound
sudo apt install -y python3-configobj
sudo apt install -y python3-constantly
sudo apt install -y python3-cryptography
sudo apt install -y python3-cups:amd64
sudo apt install -y python3-cupshelpers
sudo apt install -y python3-dbus
sudo apt install -y python3-debconf
sudo apt install -y python3-debian
sudo apt install -y python3-defer
sudo apt install -y python3-dev
sudo apt install -y python3-distro
sudo apt install -y python3-distro-info
sudo apt install -y python3-distupgrade
sudo apt install -y python3-distutils
sudo apt install -y python3-gdbm:amd64
sudo apt install -y python3-gi
sudo apt install -y python3-gi-cairo
sudo apt install -y python3-hamcrest
sudo apt install -y python3-httplib2
sudo apt install -y python3-hyperlink
sudo apt install -y python3-ibus-1.0
sudo apt install -y python3-idna
sudo apt install -y python3-importlib-metadata
sudo apt install -y python3-incremental
sudo apt install -y python3-jeepney
sudo apt install -y python3-jinja2
sudo apt install -y python3-json-pointer
sudo apt install -y python3-jsonpatch
sudo apt install -y python3-jsonschema
sudo apt install -y python3-jwt
sudo apt install -y python3-keyring
sudo apt install -y python3-launchpadlib
sudo apt install -y python3-lazr.restfulclient
sudo apt install -y python3-lazr.uri
sudo apt install -y python3-ldb
sudo apt install -y python3-lib2to3
sudo apt install -y python3-libapparmor
sudo apt install -y python3-macaroonbakery
sudo apt install -y python3-magic
sudo apt install -y python3-markupsafe
sudo apt install -y python3-minimal
sudo apt install -y python3-more-itertools
sudo apt install -y python3-mutagen
sudo apt install -y python3-nacl
sudo apt install -y python3-netifaces:amd64
sudo apt install -y python3-netplan
sudo apt install -y python3-newt:amd64
sudo apt install -y python3-oauthlib
sudo apt install -y python3-openssl
sudo apt install -y python3-pexpect
sudo apt install -y python3-pip
sudo apt install -y python3-pip-whl
sudo apt install -y python3-pkg-resources
sudo apt install -y python3-problem-report
sudo apt install -y python3-protobuf
sudo apt install -y python3-ptyprocess
sudo apt install -y python3-pyasn1
sudo apt install -y python3-pyasn1-modules
sudo apt install -y python3-pycryptodome
sudo apt install -y python3-pymacaroons
sudo apt install -y python3-pyparsing
sudo apt install -y python3-pyqt5
sudo apt install -y python3-pyqt5.qtwebchannel
sudo apt install -y python3-pyqt5.qtwebengine
sudo apt install -y python3-pyqt5.sip
sudo apt install -y python3-pyrsistent:amd64
sudo apt install -y python3-pyxattr:amd64
sudo apt install -y python3-requests
sudo apt install -y python3-rfc3339
sudo apt install -y python3-secretstorage
sudo apt install -y python3-serial
sudo apt install -y python3-service-identity
sudo apt install -y python3-setuptools
sudo apt install -y python3-setuptools-whl
sudo apt install -y python3-six
sudo apt install -y python3-software-properties
sudo apt install -y python3-systemd
sudo apt install -y python3-talloc:amd64
sudo apt install -y python3-tk:amd64
sudo apt install -y python3-twisted
sudo apt install -y python3-tz
sudo apt install -y python3-update-manager
sudo apt install -y python3-urllib3
sudo apt install -y python3-wadllib
sudo apt install -y python3-websockets
sudo apt install -y python3-wheel
sudo apt install -y python3-xdg
sudo apt install -y python3-xkit
sudo apt install -y python3-yaml
sudo apt install -y python3-zipp
sudo apt install -y python3-zope.interface
sudo apt install -y python3.10
sudo apt install -y python3.10-dev
sudo apt install -y python3.10-minimal
sudo apt install -y python3.10-venv
sudo apt install -y qt5-gtk-platformtheme:amd64
sudo apt install -y qttranslations5-l10n
sudo apt install -y rclone
sudo apt install -y readline-common
sudo apt install -y redis-server
sudo apt install -y redis-tools
sudo apt install -y ristretto
sudo apt install -y rpcsvc-proto
sudo apt install -y rsync
sudo apt install -y rsyslog
sudo apt install -y rtkit
sudo apt install -y rtmpdump
sudo apt install -y run-one
sudo apt install -y rygel
sudo apt install -y samba-libs:amd64
sudo apt install -y sane-airscan
sudo apt install -y sane-utils
sudo apt install -y sbsigntool
sudo apt install -y screen
sudo apt install -y screen-resolution-extra
sudo apt install -y secureboot-db
sudo apt install -y sed
sudo apt install -y sensible-utils
sudo apt install -y session-migration
sudo apt install -y sg3-utils
sudo apt install -y sg3-utils-udev
sudo apt install -y sgml-base
sudo apt install -y sgml-data
sudo apt install -y shared-mime-info
sudo apt install -y snapd
sudo apt install -y sntp
sudo apt install -y software-properties-common
sudo apt install -y sosreport
sudo apt install -y sound-theme-freedesktop
sudo apt install -y squashfs-tools
sudo apt install -y ssh-import-id
sudo apt install -y ssl-cert
sudo apt install -y strace
sudo apt install -y sublime-text
sudo apt install -y sudo
sudo apt install -y switcheroo-control
sudo apt install -y system-config-printer
sudo apt install -y system-config-printer-common
sudo apt install -y system-config-printer-udev
sudo apt install -y systemd
sudo apt install -y systemd-hwe-hwdb
sudo apt install -y systemd-sysv
sudo apt install -y sysvinit-utils
sudo apt install -y tango-icon-theme
sudo apt install -y tar
sudo apt install -y tcl
sudo apt install -y tcl8.6
sudo apt install -y tcpdump
sudo apt install -y telnet
sudo apt install -y thermald
sudo apt install -y thin-provisioning-tools
sudo apt install -y thunar
sudo apt install -y thunar-archive-plugin
sudo apt install -y thunar-data
sudo apt install -y thunar-media-tags-plugin
sudo apt install -y thunar-volman
sudo apt install -y tightvncpasswd
sudo apt install -y tightvncserver
sudo apt install -y time
sudo apt install -y timgm6mb-soundfont
sudo apt install -y tk8.6-blt2.5
sudo apt install -y tmux
sudo apt install -y tnftp
sudo apt install -y tpm-udev
sudo apt install -y tree
sudo apt install -y tumbler:amd64
sudo apt install -y tumbler-common
sudo apt install -y tzdata
sudo apt install -y ubuntu-advantage-tools
sudo apt install -y ubuntu-docs
sudo apt install -y ubuntu-drivers-common
sudo apt install -y ubuntu-keyring
sudo apt install -y ubuntu-minimal
sudo apt install -y ubuntu-mono
sudo apt install -y ubuntu-pro-client
sudo apt install -y ubuntu-pro-client-l10n
sudo apt install -y ubuntu-release-upgrader-core
sudo apt install -y ubuntu-server
sudo apt install -y ubuntu-server-minimal
sudo apt install -y ubuntu-standard
sudo apt install -y ubuntu-touch-sounds
sudo apt install -y ubuntu-wallpapers
sudo apt install -y ubuntu-wallpapers-jammy
sudo apt install -y ucf
sudo apt install -y udev
sudo apt install -y udisks2
sudo apt install -y ufw
sudo apt install -y unattended-upgrades
sudo apt install -y unity-control-center
sudo apt install -y unity-greeter
sudo apt install -y unity-gtk-module-common
sudo apt install -y unity-gtk2-module:amd64
sudo apt install -y unity-gtk3-module:amd64
sudo apt install -y unity-settings-daemon
sudo apt install -y unity-settings-daemon-schemas
sudo apt install -y unrar
sudo apt install -y unzip
sudo apt install -y update-inetd
sudo apt install -y update-manager-core
sudo apt install -y update-notifier-common
sudo apt install -y upower
sudo apt install -y usb-modeswitch
sudo apt install -y usb-modeswitch-data
sudo apt install -y usb.ids
sudo apt install -y usbmuxd
sudo apt install -y usbutils
sudo apt install -y usrmerge
sudo apt install -y util-linux
sudo apt install -y uuid-dev:amd64
sudo apt install -y uuid-runtime
sudo apt install -y va-driver-all:amd64
sudo apt install -y vdpau-driver-all:amd64
sudo apt install -y vim
sudo apt install -y vim-common
sudo apt install -y vim-runtime
sudo apt install -y vim-tiny
sudo apt install -y wamerican
sudo apt install -y wayland-protocols
sudo apt install -y wget
sudo apt install -y whiptail
sudo apt install -y whois
sudo apt install -y whoopsie
sudo apt install -y whoopsie-preferences
sudo apt install -y wireless-regdb
sudo apt install -y wpasupplicant
sudo apt install -y x11-apps
sudo apt install -y x11-common
sudo apt install -y x11-session-utils
sudo apt install -y x11-utils
sudo apt install -y x11-xfs-utils
sudo apt install -y x11-xkb-utils
sudo apt install -y x11-xserver-utils
sudo apt install -y x11proto-dev
sudo apt install -y xarchiver
sudo apt install -y xauth
sudo apt install -y xbitmaps
sudo apt install -y xcvt
sudo apt install -y xdg-dbus-proxy
sudo apt install -y xdg-desktop-portal
sudo apt install -y xdg-desktop-portal-gtk
sudo apt install -y xdg-user-dirs
sudo apt install -y xdg-utils
sudo apt install -y xfburn
sudo apt install -y xfce4
sudo apt install -y xfce4-appfinder
sudo apt install -y xfce4-battery-plugin
sudo apt install -y xfce4-clipman
sudo apt install -y xfce4-clipman-plugin:amd64
sudo apt install -y xfce4-cpufreq-plugin:amd64
sudo apt install -y xfce4-cpugraph-plugin:amd64
sudo apt install -y xfce4-datetime-plugin:amd64
sudo apt install -y xfce4-dict
sudo apt install -y xfce4-diskperf-plugin:amd64
sudo apt install -y xfce4-fsguard-plugin:amd64
sudo apt install -y xfce4-genmon-plugin:amd64
sudo apt install -y xfce4-goodies
sudo apt install -y xfce4-helpers
sudo apt install -y xfce4-mailwatch-plugin
sudo apt install -y xfce4-netload-plugin
sudo apt install -y xfce4-notifyd
sudo apt install -y xfce4-panel
sudo apt install -y xfce4-places-plugin
sudo apt install -y xfce4-power-manager
sudo apt install -y xfce4-power-manager-data
sudo apt install -y xfce4-power-manager-plugins
sudo apt install -y xfce4-pulseaudio-plugin:amd64
sudo apt install -y xfce4-screensaver
sudo apt install -y xfce4-screenshooter
sudo apt install -y xfce4-sensors-plugin
sudo apt install -y xfce4-session
sudo apt install -y xfce4-settings
sudo apt install -y xfce4-smartbookmark-plugin:amd64
sudo apt install -y xfce4-systemload-plugin:amd64
sudo apt install -y xfce4-taskmanager
sudo apt install -y xfce4-terminal
sudo apt install -y xfce4-timer-plugin:amd64
sudo apt install -y xfce4-verve-plugin:amd64
sudo apt install -y xfce4-wavelan-plugin:amd64
sudo apt install -y xfce4-weather-plugin:amd64
sudo apt install -y xfce4-whiskermenu-plugin:amd64
sudo apt install -y xfce4-xkb-plugin:amd64
sudo apt install -y xfconf
sudo apt install -y xfdesktop4
sudo apt install -y xfdesktop4-data
sudo apt install -y xfonts-100dpi
sudo apt install -y xfonts-75dpi
sudo apt install -y xfonts-base
sudo apt install -y xfonts-cyrillic
sudo apt install -y xfonts-encodings
sudo apt install -y xfonts-scalable
sudo apt install -y xfonts-utils
sudo apt install -y xfsprogs
sudo apt install -y xfwm4
sudo apt install -y xiccd
sudo apt install -y xinit
sudo apt install -y xinput
sudo apt install -y xkb-data
sudo apt install -y xml-core
sudo apt install -y xorg
sudo apt install -y xorg-docs-core
sudo apt install -y xorg-sgml-doctools
sudo apt install -y xserver-common
sudo apt install -y xserver-xephyr
sudo apt install -y xserver-xorg
sudo apt install -y xserver-xorg-core
sudo apt install -y xserver-xorg-input-all
sudo apt install -y xserver-xorg-input-libinput
sudo apt install -y xserver-xorg-input-wacom
sudo apt install -y xserver-xorg-legacy
sudo apt install -y xserver-xorg-video-all
sudo apt install -y xserver-xorg-video-amdgpu
sudo apt install -y xserver-xorg-video-ati
sudo apt install -y xserver-xorg-video-dummy
sudo apt install -y xserver-xorg-video-fbdev
sudo apt install -y xserver-xorg-video-intel
sudo apt install -y xserver-xorg-video-nouveau
sudo apt install -y xserver-xorg-video-nvidia-470
sudo apt install -y xserver-xorg-video-qxl
sudo apt install -y xserver-xorg-video-radeon
sudo apt install -y xserver-xorg-video-vesa
sudo apt install -y xserver-xorg-video-vmware
sudo apt install -y xterm
sudo apt install -y xtrans-dev
sudo apt install -y xvfb
sudo apt install -y xwayland
sudo apt install -y xxd
sudo apt install -y xz-utils
sudo apt install -y yaru-theme-gnome-shell
sudo apt install -y yelp
sudo apt install -y yelp-xsl
sudo apt install -y yt-dlp
sudo apt install -y zeitgeist-core
sudo apt install -y zenity
sudo apt install -y zenity-common
sudo apt install -y zerofree
sudo apt install -y zip
sudo apt install -y zlib1g:amd64
sudo apt install -y zlib1g-dev:amd64
