name: Bug report
description: Report a bug in our project
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        # IMPORTANT - Read and follow these instructions carefully. Help us help you.

        ### Does issue already exist?

        Use the search tool. Don't annoy everyone by duplicating existing Issues.

        ### Are you up-to-date?

        Upgrade to the latest version and confirm the issue/bug is still there.

        `$ pip install yfinance --upgrade --no-cache-dir`

        Confirm by running:

        `import yfinance as yf ; print(yf.__version__)`

        and comparing against [PIP](https://pypi.org/project/yfinance/#history).

        ### Does Yahoo actually have the data?

        Are you spelling symbol *exactly* same as Yahoo?

        Then visit `finance.yahoo.com` and confirm they have the data you want. Maybe your symbol was delisted, or your expectations of `yfinance` are wrong.

        ### Are you spamming Yahoo?

        Yahoo Finance free service has rate-limiting https://github.com/ranaroussi/yfinance/discussions/1513. Once limit hit, Yahoo can delay, block, or return bad data -> not a `yfinance` bug.
        
  - type: markdown
    attributes:
      value: |
        ---
        ## Still think it's a bug?

        Provide the following as best you can:

  - type: textarea
    id: code
    attributes:
      label: "Simple code that reproduces your problem"
      description: "Provide a snippet of code that we can copy-paste-run. Wrap code in Python Markdown code blocks for proper formatting (```` ```python ... ``` ````)."
    validations:
      required: true

  - type: textarea
    id: debug-log
    attributes:
      label: "Debug log"
      description: "Run code with debug logging enabled and post the full output. Instructions: https://github.com/ranaroussi/yfinance/tree/main#logging"
    validations:
      required: true

  - type: textarea
    id: bad-data-proof
    attributes:
      label: "Bad data proof"
      description: "If you think `yfinance` returning bad data, provide your proof here."
    validations:
      required: false

  - type: input
    id: version-yfinance
    attributes:
      label: "`yfinance` version"
    validations:
      required: true

  - type: input
    id: version-python
    attributes:
      label: "Python version"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: "Operating system"
    validations:
      required: false
