# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing.proto
"""Generated protocol buffer code."""

import base64
from typing import cast

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_SERIALIZED_PRICING_PROTO = base64.b64decode(
    "Cg1wcmljaW5nLnByb3RvIpoFCgtQcmljaW5nRGF0YRIKCgJpZBgBIAEoCRINCgVwcmljZRgCIAEo"
    "AhIMCgR0aW1lGAMgASgSEhAKCGN1cnJlbmN5GAQgASgJEhAKCGV4Y2hhbmdlGAUgASgJEhIKCnF1"
    "b3RlX3R5cGUYBiABKAUSFAoMbWFya2V0X2hvdXJzGAcgASgFEhYKDmNoYW5nZV9wZXJjZW50GAgg"
    "ASgCEhIKCmRheV92b2x1bWUYCSABKBISEAoIZGF5X2hpZ2gYCiABKAISDwoHZGF5X2xvdxgLIAEo"
    "AhIOCgZjaGFuZ2UYDCABKAISEgoKc2hvcnRfbmFtZRgNIAEoCRITCgtleHBpcmVfZGF0ZRgOIAEo"
    "EhISCgpvcGVuX3ByaWNlGA8gASgCEhYKDnByZXZpb3VzX2Nsb3NlGBAgASgCEhQKDHN0cmlrZV9w"
    "cmljZRgRIAEoAhIZChF1bmRlcmx5aW5nX3N5bWJvbBgSIAEoCRIVCg1vcGVuX2ludGVyZXN0GBMg"
    "ASgSEhQKDG9wdGlvbnNfdHlwZRgUIAEoEhITCgttaW5pX29wdGlvbhgVIAEoEhIRCglsYXN0X3Np"
    "emUYFiABKBISCwoDYmlkGBcgASgCEhAKCGJpZF9zaXplGBggASgSEgsKA2FzaxgZIAEoAhIQCghh"
    "c2tfc2l6ZRgaIAEoEhISCgpwcmljZV9oaW50GBsgASgSEhAKCHZvbF8yNGhyGBwgASgSEhoKEnZv"
    "bF9hbGxfY3VycmVuY2llcxgdIAEoEhIVCg1mcm9tX2N1cnJlbmN5GB4gASgJEhMKC2xhc3RfbWFy"
    "a2V0GB8gASgJEhoKEmNpcmN1bGF0aW5nX3N1cHBseRggIAEoARISCgptYXJrZXRfY2FwGCEgASgB"
    "YgZwcm90bzM="
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(_SERIALIZED_PRICING_PROTO)

_PRICINGDATA = DESCRIPTOR.message_types_by_name["PricingData"]
PricingData = cast(
    type[_message.Message],
    _reflection.GeneratedProtocolMessageType(
        "PricingData",
        (_message.Message,),
        {
            "DESCRIPTOR": _PRICINGDATA,
            "__module__": "pricing_pb2",
            # @@protoc_insertion_point(class_scope:PricingData)
        },
    ),
)
_sym_db.RegisterMessage(PricingData)

if not getattr(_descriptor, "_USE_C_DESCRIPTORS"):
    setattr(DESCRIPTOR, "_options", None)
    setattr(_PRICINGDATA, "_serialized_start", 18)
    setattr(_PRICINGDATA, "_serialized_end", 684)
# @@protoc_insertion_point(module_scope)
