name: Ruff
on:
  pull_request:
    branches:
      - master
      - main
      - dev
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync
      - name: Run ruff
        run: uv run ruff check . --exclude yfinance/pricing_pb2.py
